<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DatosEconomicosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Año para el cual se cargarán los datos
        $anio = 2024;

        // ID del usuario que realiza la carga (asumiendo que el usuario con ID 1 es un administrador)
        $userId = 1;

        // ID del estado (2 = 'Enviado' según la migración)
        $estadoId = 2;

        // Datos económicos a insertar o actualizar
        $datosEconomicos = [
            [
                'cue' => '20024000',
                'monto_anual' => 34000.00,
                'monto_mensual' => 43700.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20053100',
                'monto_anual' => 66000.00,
                'monto_mensual' => 41528.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 8305.00,
                'observaciones' => 'El monto de la matrícula es para agosto 2024. Se cobran 2 módulos extraprogramáticos en 1er año, 1 en segundo, y cero o 1 en tercer año, dependiendo la carrera. Cada módulo es $8.305.',
            ],
            [
                'cue' => '20053900',
                'monto_anual' => 54000.00,
                'monto_mensual' => 48680.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 18270.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20089000',
                'monto_anual' => 3000.00,
                'monto_mensual' => 3000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Nuestra escuela es sindical, por esta razón tenemos precios diferenciados entre AFILIADOS y NO AFILIADOS. Los NO AFILIADOS abonan $3000 de inscripción y $3000 de matrícula.',
            ],
            [
                'cue' => '20096900',
                'monto_anual' => 22500.00,
                'monto_mensual' => 22500.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Se tiene un internado las alumnas que viven en el mismo tienen un arancel diferencial que es de $27500',
            ],
            [
                'cue' => '20142000',
                'monto_anual' => 40000.00,
                'monto_mensual' => 40000.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20174400',
                'monto_anual' => 90000.00,
                'monto_mensual' => 47260.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20191900',
                'monto_anual' => 31500.00,
                'monto_mensual' => 33216.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 6643.20,
                'observaciones' => '',
            ],
            [
                'cue' => '20224200',
                'monto_anual' => 33000.00,
                'monto_mensual' => 42000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20234600',
                'monto_anual' => 30000.00,
                'monto_mensual' => 45000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20245000',
                'monto_anual' => 22000.00,
                'monto_mensual' => 16000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20282200',
                'monto_anual' => 50000.00,
                'monto_mensual' => 42000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20282300',
                'monto_anual' => 35000.00,
                'monto_mensual' => 30000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20286200',
                'monto_anual' => 15000.00,
                'monto_mensual' => 33000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20299400',
                'monto_anual' => 12600.00,
                'monto_mensual' => 20000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Se envió el formulario en el pedido anterior.',
            ],
            [
                'cue' => '20304900',
                'monto_anual' => 30000.00,
                'monto_mensual' => 30000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '20314900',
                'monto_anual' => 0.00,
                'monto_mensual' => 0.00,
                'cantidad_cuota' => 0,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Esta institución es cuota 0 (cero). No se cobra suma alguna por ningún concepto.',
            ],
            [
                'cue' => '60011700',
                'monto_anual' => 22000.00,
                'monto_mensual' => 26000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '60021000',
                'monto_anual' => 0.00,
                'monto_mensual' => 0.00,
                'cantidad_cuota' => 0,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El Instituto depende de la Secretaría de Educación de la Municipalidad de General Pueyrredón y sus carreras son gratuitas',
            ],
            [
                'cue' => '60167400',
                'monto_anual' => 43000.00,
                'monto_mensual' => 62000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '60611700',
                'monto_anual' => 51509.76,
                'monto_mensual' => 34339.84,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 7795.20,
                'observaciones' => 'El monto extracurricular se encuentra dentro del valor total de la cuota mensual',
            ],
            [
                'cue' => '60643100',
                'monto_anual' => 59724.00,
                'monto_mensual' => 72000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'La inscripción de 1ro y 2do fue de $59724 y de 3er año $29800. Además los alumnos becados pagan el 50% tanto de la matrícula como de las 10 cuotas.',
            ],
            [
                'cue' => '60652600',
                'monto_anual' => 30000.00,
                'monto_mensual' => 27710.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '60831300',
                'monto_anual' => 30000.00,
                'monto_mensual' => 32840.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 10050.00,
                'observaciones' => '',
            ],
            [
                'cue' => '60863000',
                'monto_anual' => 40924.80,
                'monto_mensual' => 43400.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '60877900',
                'monto_anual' => 27658.80,
                'monto_mensual' => 30892.80,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '61185300',
                'monto_anual' => 22486.00,
                'monto_mensual' => 28410.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El valor de la cuota corresponde al mes de mayo',
            ],
            [
                'cue' => '61233400',
                'monto_anual' => 37000.00,
                'monto_mensual' => 44800.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 8200.00,
                'observaciones' => 'La cuota final es de $53.000 siendo la cuota extracurricular parte integrante de la cuota mensual.',
            ],
            [
                'cue' => '61337200',
                'monto_anual' => 25111.00,
                'monto_mensual' => 28641.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El arancel autorizado para el mes de Mayo es de $30.641. Considerando la actual situación económica y el costo del transporte se decidió aplicar una bonificación de $2.000. Por lo que el arancel a pagar es de $28.641.',
            ],
            [
                'cue' => '61578100',
                'monto_anual' => 45000.00,
                'monto_mensual' => 60000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '62111300',
                'monto_anual' => 0.00,
                'monto_mensual' => 0.00,
                'cantidad_cuota' => 0,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'La Municipalidad de Lomas de Zamora es propietarios de esta institución, motivo por el cual No se cobra arancel a los alumnos.',
            ],
            [
                'cue' => '62385500',
                'monto_anual' => 6800.00,
                'monto_mensual' => 6800.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 10.00,
                'observaciones' => 'Las cuotas Extracurriculares no son obligatorias y el alumno que desea puede cursar esas materias que son Gestión Emocional, y Lengua de señas',
            ],
            [
                'cue' => '140233600',
                'monto_anual' => 55000.00,
                'monto_mensual' => 25000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140261700',
                'monto_anual' => 24000.00,
                'monto_mensual' => 25000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140319700',
                'monto_anual' => 45000.00,
                'monto_mensual' => 42000.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140322200',
                'monto_anual' => 29000.00,
                'monto_mensual' => 26000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140333900',
                'monto_anual' => 55000.00,
                'monto_mensual' => 40000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140443800',
                'monto_anual' => 105000.00,
                'monto_mensual' => 63480.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140463300',
                'monto_anual' => 20000.00,
                'monto_mensual' => 20000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140488900',
                'monto_anual' => 65000.00,
                'monto_mensual' => 40000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510100',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510101',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510102',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510103',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510104',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510105',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510106',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510107',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140510108',
                'monto_anual' => 30000.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '140532900',
                'monto_anual' => 65000.00,
                'monto_mensual' => 50000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Instituto sin aportes estatales',
            ],
            [
                'cue' => '180121600',
                'monto_anual' => 8000.00,
                'monto_mensual' => 18000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Aún no recibimos las mochilas del Pronafe 2023',
            ],
            [
                'cue' => '180143000',
                'monto_anual' => 51000.00,
                'monto_mensual' => 31000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '260061100',
                'monto_anual' => 12000.00,
                'monto_mensual' => 12000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Solo se le cobra a los estudiantes que no son afiliados a ATSA Chubut',
            ],
            [
                'cue' => '260061101',
                'monto_anual' => 12000.00,
                'monto_mensual' => 12000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Solo se le cobra a los estudiantes que no son afiliados a ATSA Chubut',
            ],
            [
                'cue' => '300029300',
                'monto_anual' => 25000.00,
                'monto_mensual' => 26500.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '300201100',
                'monto_anual' => 16000.00,
                'monto_mensual' => 18000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Las cuotas se actualizan cada dos meses.',
            ],
            [
                'cue' => '300251300',
                'monto_anual' => 0.00,
                'monto_mensual' => 15000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '380098400',
                'monto_anual' => 8000.00,
                'monto_mensual' => 28000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '500132400',
                'monto_anual' => 30000.00,
                'monto_mensual' => 35829.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 6971.00,
                'observaciones' => 'Se cobran 10 cuotas anuales que se componen de un arancel programático (de $35829 a junio de 2024) y de un arancel extra programático (de $6971 a junio de 2024)',
            ],
            [
                'cue' => '500180400',
                'monto_anual' => 30000.00,
                'monto_mensual' => 30000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Seria de vital importancia la actualización de Becas (monto) debido a que muchos de nuestros alumnos necesitan de la beca para dar continuidad a sus estudios y desde Instituto IDICSA no se percibe ningún tipo de ayuda económica provincial o nacional. Esto hace que solo se pueda solventar la Institución con la cuota de los alumnos.',
            ],
            [
                'cue' => '500180401',
                'monto_anual' => 30000.00,
                'monto_mensual' => 28000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Seria de vital importancia la actualización de Becas (monto) debido a que muchos de nuestros alumnos necesitan de la beca para dar continuidad a sus estudios y desde Instituto IDICSA no se percibe ningún tipo de ayuda económica provincial o nacional. Esto hace que solo se pueda solventar la Institución con la cuota de los alumnos.',
            ],
            [
                'cue' => '500180402',
                'monto_anual' => 30000.00,
                'monto_mensual' => 30000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Seria de vital importancia la actualización de Becas (monto) debido a que muchos de nuestros alumnos necesitan de la beca para dar continuidad a sus estudios y desde Instituto IDICSA no se percibe ningún tipo de ayuda económica provincial o nacional. Esto hace que solo se pueda solventar la Institución con la cuota de los alumnos.',
            ],
            [
                'cue' => '500180404',
                'monto_anual' => 30000.00,
                'monto_mensual' => 28000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Seria de vital importancia la actualización de Becas (monto) debido a que muchos de nuestros alumnos necesitan de la beca para dar continuidad a sus estudios y desde Instituto IDICSA no se percibe ningún tipo de ayuda económica provincial o nacional. Esto hace que solo se pueda solventar la Institución con la cuota de los alumnos.',
            ],
            [
                'cue' => '500180406',
                'monto_anual' => 30000.00,
                'monto_mensual' => 28000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Seria de vital importancia la actualización de Becas (monto) debido a que muchos de nuestros alumnos necesitan de la beca para dar continuidad a sus estudios y desde Instituto IDICSA no se percibe ningún tipo de ayuda económica provincial o nacional. Esto hace que solo se pueda solventar la Institución con la cuota de los alumnos.',
            ],
            [
                'cue' => '500238900',
                'monto_anual' => 25000.00,
                'monto_mensual' => 36000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El instituto no recibe ningún tipo de subsidio.',
            ],
            [
                'cue' => '540027900',
                'monto_anual' => 52400.00,
                'monto_mensual' => 25000.00,
                'cantidad_cuota' => 9,
                'monto_extracurricular' => 31500.00,
                'observaciones' => 'Incluye seguro (incluye cortopunzantes), insumos para el gabinete de simulación y el hospital (elementos de bioseguridad), alojamiento y comida (en el caso de la residencia).',
            ],
            [
                'cue' => '540153300',
                'monto_anual' => 0.00,
                'monto_mensual' => 0.00,
                'cantidad_cuota' => 0,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El IMES no Cobra ningún tipo de Cuota',
            ],
            [
                'cue' => '540186600',
                'monto_anual' => 19000.00,
                'monto_mensual' => 25000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Nuestra Institución es NO Subvencionado.',
            ],
            [
                'cue' => '580075500',
                'monto_anual' => 0.00,
                'monto_mensual' => 0.00,
                'cantidad_cuota' => 0,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '580075500',
                'monto_anual' => 16500.00,
                'monto_mensual' => 20000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '580108100',
                'monto_anual' => 27000.00,
                'monto_mensual' => 30000.00,
                'cantidad_cuota' => 11,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '620100300',
                'monto_anual' => 44500.00,
                'monto_mensual' => 49088.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '620100301',
                'monto_anual' => 44500.00,
                'monto_mensual' => 49088.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '620100302',
                'monto_anual' => 44500.00,
                'monto_mensual' => 49088.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '620100305',
                'monto_anual' => 44500.00,
                'monto_mensual' => 49088.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '620100306',
                'monto_anual' => 44500.00,
                'monto_mensual' => 49088.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '660063300',
                'monto_anual' => 60000.00,
                'monto_mensual' => 81000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'Las cuotas fueron variando desde marzo hasta mayo',
            ],
            [
                'cue' => '660117400',
                'monto_anual' => 35000.00,
                'monto_mensual' => 46000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '660117401',
                'monto_anual' => 35000.00,
                'monto_mensual' => 46000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '660117408',
                'monto_anual' => 35000.00,
                'monto_mensual' => 46000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '660117410',
                'monto_anual' => 35000.00,
                'monto_mensual' => 46000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820017501',
                'monto_anual' => 15000.00,
                'monto_mensual' => 40000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820061900',
                'monto_anual' => 120000.00,
                'monto_mensual' => 27000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820061901',
                'monto_anual' => 120000.00,
                'monto_mensual' => 27000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820104900',
                'monto_anual' => 15000.00,
                'monto_mensual' => 13000.00,
                'cantidad_cuota' => 9,
                'monto_extracurricular' => 2000.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820188400',
                'monto_anual' => 60000.00,
                'monto_mensual' => 35290.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820188401',
                'monto_anual' => 32000.00,
                'monto_mensual' => 24000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'El plan de cuotas comprende la matrícula en febrero y 10 cuotas de marzo a diciembre inclusive.',
            ],
            [
                'cue' => '820188402',
                'monto_anual' => 16000.00,
                'monto_mensual' => 20000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820250700',
                'monto_anual' => 30000.00,
                'monto_mensual' => 24480.00,
                'cantidad_cuota' => 9,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820381400',
                'monto_anual' => 40000.00,
                'monto_mensual' => 22740.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820382000',
                'monto_anual' => 60000.00,
                'monto_mensual' => 35000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820412100',
                'monto_anual' => 40000.00,
                'monto_mensual' => 39000.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '820413900',
                'monto_anual' => 54000.00,
                'monto_mensual' => 51000.00,
                'cantidad_cuota' => 12,
                'monto_extracurricular' => 1500.00,
                'observaciones' => 'Los estudiantes de 1° año abona 10 cuotas mensuales, los estudiantes de 2° y 3° año abonan 12 cuotas mensuales, pero NO abonan matricula anual',
            ],
            [
                'cue' => '860187600',
                'monto_anual' => 40000.00,
                'monto_mensual' => 20000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => '',
            ],
            [
                'cue' => '860220000',
                'monto_anual' => 20000.00,
                'monto_mensual' => 10000.00,
                'cantidad_cuota' => 10,
                'monto_extracurricular' => 0.00,
                'observaciones' => 'no tenemos subvención',
            ],
        ];

        foreach ($datosEconomicos as $dato) {
            $institutoExiste = DB::table('institutos')
                ->where('cue', $dato['cue'])
                ->exists();

            if (!$institutoExiste) {
                $this->command->warn("Se omite CUE inexistente en institutos: " . $dato['cue']);
                continue;
            }

            // Verificar si ya existe un registro para este CUE y año
            $registroExistente = DB::table('datos')
                ->where('cue', $dato['cue'])
                ->where('anio', $anio)
                ->first();

            // Preparar los datos a actualizar/insertar
            $datosActualizados = [
                'monto_anual' => $dato['monto_anual'],
                'monto_mensual' => $dato['monto_mensual'],
                'cantidad_cuota' => $dato['cantidad_cuota'],
                'monto_extracurricular' => $dato['monto_extracurricular'],
                'observaciones' => $dato['observaciones'],
                'estado_id' => $estadoId,
                'user_id' => $userId,
                'updated_at' => Carbon::now(),
            ];

            if ($registroExistente) {
                // Si el registro existe, actualizamos solo los campos económicos
                DB::table('datos')
                    ->where('id', $registroExistente->id)
                    ->update($datosActualizados);
                
                $this->command->info("Datos económicos actualizados para el CUE: " . $dato['cue']);
            } else {
                // Si no existe, creamos un nuevo registro con los datos económicos
                $datosActualizados['anio'] = $anio;
                $datosActualizados['cue'] = $dato['cue'];
                $datosActualizados['created_at'] = Carbon::now();
                
                DB::table('datos')->insert($datosActualizados);
                
                $this->command->info("Nuevo registro con datos económicos creado para el CUE: " . $dato['cue']);
            }
        }
    }
}
