<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DepartamentosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Primero obtenemos el ID de cada provincia
        $provincias = DB::table('provincias')->pluck('id', 'descripcion');

        $departamentos = [
            // Buenos Aires
            ['descripcion' => 'Loberia', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Hurlingham', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Pueyrredon', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Pinto', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Punta Indio', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Bragado', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Nicolas', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Carlos Casares', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Lomas de Zamora', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Viamonte', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Rodriguez', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Gral. Juan Madariaga', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Vicente', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Las Heras', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Pedro', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Chascomús', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Coronel Suarez', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Zárate', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Morón', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'La Plata', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Fernando', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Adolfo Gonzales Chaves', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Puan', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Carlos Tejedor', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Coronel Pringles', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Tapalqué', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'La Costa', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Salto', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Dolores', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Brandsen', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Capitán Sarmiento', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Mar Chiquita', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Chacabuco', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'La Matanza', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Almirante Brown', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Rauch', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Tres de Febrero', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Luján', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Gral. Lamadrid', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Miguel', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Ayacucho', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Colón', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Trenque Lauquen', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Pilar', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Guamini', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Rojas', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Lanús', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Tornquist', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Cayetano', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Isidro', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Moreno', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Baradero', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Vicente López', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Salliquelo', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Las Flores', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Tandil', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Alvarado', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Bahía Blanca', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Florencio Varela', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Campana', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Villa Gesell', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Florentino Ameghino', 'provincia_id' => $provincias['Buenos Aires']],
         
            ['descripcion' => 'Lezama', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Presidente Péron', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Roque Pérez', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Ramallo', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Tres Lomas', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Coronel Dorrego', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Haedo', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Leando N. Alem', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Obligado', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Avellaneda', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'San Nicolás de los Arroyos', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'General Alvarado', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'La Costa', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'Puan', 'provincia_id' => $provincias['Buenos Aires']],
            ['descripcion' => 'La Plata', 'provincia_id' => $provincias['Buenos Aires']],
            


            // CABA
            ['descripcion' => 'CABA', 'provincia_id' => $provincias['CABA']],
            

            // Catamarca
            ['descripcion' => 'La Paz', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Andalgalá', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Belén', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Capayán', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Pomán', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Valle Viejo', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Catamarca']],
            ['descripcion' => 'Valle Viejo', 'provincia_id' => $provincias['Catamarca']],

            // Córdoba
            ['descripcion' => 'San Justo', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Punilla', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'General San Martín', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Punilla', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Unión', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Río Primero', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Rio Primero', 'provincia_id' => $provincias['Córdoba']],  // Alias para compatibilidad
            ['descripcion' => 'Río II', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Juárez Celman', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Cruz del Eje', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'San Javier', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Rio Cuarto', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Rio Segundo', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Colón', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Tercero Arriba', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Marcos Juarez', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Ischilín', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Calamuchita', 'provincia_id' => $provincias['Córdoba']],
            ['descripcion' => 'Sobremonte', 'provincia_id' => $provincias['Córdoba']],

            // Corrientes
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Curuzú Cuatiá', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Santo Tomé', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Esquina', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Mercedes', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Paso de los Libres', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Empedrado', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'San Roque', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'General Paz', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Lavalle', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Itatí', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Saladas', 'provincia_id' => $provincias['Corrientes']],
            ['descripcion' => 'Ensaladas', 'provincia_id' => $provincias['Corrientes']],

            // Chaco
            ['descripcion' => 'San Fernando', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Comandante Fernández', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Libertador General de San Martín', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Mayor Jorge Luis Fontana', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Gral. Güemes', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Libertad', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Chacabuco', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Bermejo', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Sargento Cabral', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Libertador General de San Martín', 'provincia_id' => $provincias['Chaco']],
            ['descripcion' => 'Alcalde Jorge Luis Fontana', 'provincia_id' => $provincias['Chaco']],

            // Chubut
            ['descripcion' => 'Rawson', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Escalante', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Biedma', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Cushamen', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Futaleufú', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Gaiman', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Gastre', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Languiñeo', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Mártires', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Paso de Indios', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Río Senguerr', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Sarmiento', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Tehuelches', 'provincia_id' => $provincias['Chubut']],
            ['descripcion' => 'Telsen', 'provincia_id' => $provincias['Chubut']],

            // Entre Ríos
            ['descripcion' => 'Paraná', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Islas del Ibicuy', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Feliciano', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Tala', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Gualeguaychú', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Diamante', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Federal', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'La Paz', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Nogoyá', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Concordia', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Gualeguay', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Victoria', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Villaguay', 'provincia_id' => $provincias['Entre Ríos']],
            ['descripcion' => 'Federación', 'provincia_id' => $provincias['Entre Ríos']],

            // Jujuy
            ['descripcion' => 'Ledesma', 'provincia_id' => $provincias['Jujuy']],
            ['descripcion' => 'Cochinoca', 'provincia_id' => $provincias['Jujuy']],
            ['descripcion' => 'Dr. Manuel Belgrano', 'provincia_id' => $provincias['Jujuy']],
            ['descripcion' => 'San Pedro', 'provincia_id' => $provincias['Jujuy']],
            ['descripcion' => 'Yavi', 'provincia_id' => $provincias['Jujuy']],

            // Mendoza
            ['descripcion' => 'San Carlos', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Luján de Cuyo', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Santa Rosa', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'General Alvear', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Guaymallén', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'San Rafael', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Tunuyán', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Rivadavia', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Luján de Cuyo', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Santa Rosa', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'General Alvear', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'San Martin', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Lavalle', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Tupungato', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Malargüe', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Maipú', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Las Heras', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'Godoy Cruz', 'provincia_id' => $provincias['Mendoza']],
            ['descripcion' => 'San Martín', 'provincia_id' => $provincias['Mendoza']],

            // Misiones
            ['descripcion' => 'Leandro N. Alem', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Eldorado', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Iguazú', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Oberá', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'San Ignacio', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => '25 de Mayo', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Cainguás', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Libertador General San Martín', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'San Pedro', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Montecarlo', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'San Javier', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Guaraní', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'San Martín', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Candelaria', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Concepción', 'provincia_id' => $provincias['Misiones']],
            ['descripcion' => 'Apóstoles', 'provincia_id' => $provincias['Misiones']],

            // Neuquén
            ['descripcion' => 'Confluencia', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Zapala', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Los Lagos', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Picún Leufú', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Lácar', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Huiliches', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Aluminé', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Añelo', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Catán Lil', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Chos Malal', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Collón Curá', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Loncopué', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Minas', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Ñorquín', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Pehuenches', 'provincia_id' => $provincias['Neuquén']],
            ['descripcion' => 'Picunches', 'provincia_id' => $provincias['Neuquén']],

            // Río Negro
            ['descripcion' => 'General Roca', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'San Carlos de Bariloche', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'San Antonio Oeste', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Avellaneda', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'El Cuy', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Veinticinco de Mayo', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Pichi Mahuida', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Valcheta', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Ñorquinco', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Pilcaniyeu', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Nueve de Julio', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Adolfo Alsina', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Cinco Saltos', 'provincia_id' => $provincias['Rio Negro']],

            ['descripcion' => 'Bariloche', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'San Antonio', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => '25 de Mayo', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => 'Ñorquincó', 'provincia_id' => $provincias['Rio Negro']],
            ['descripcion' => '9 de Julio', 'provincia_id' => $provincias['Rio Negro']],
           

        

            // Salta
            ['descripcion' => 'General José de San Martín', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Rosario de Lerma', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Orán', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'General Güemes', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Anta', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Chicoana', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Rosario de la Frontera', 'provincia_id' => $provincias['Salta']],
            ['descripcion' => 'Cachi', 'provincia_id' => $provincias['Salta']],

            // Santa Fe
            ['descripcion' => 'San Justo', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Iriondo', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Rosario', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'La Capital', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'General López', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Las Colonias', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'San Lorenzo', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'San Cristóbal', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Vera', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'General Obligado', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Castellanos', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'San Martín', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Nueve de Julio', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'San Jerónimo', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Caseros', 'provincia_id' => $provincias['Santa Fe']],
            ['descripcion' => 'Belgrano', 'provincia_id' => $provincias['Santa Fe']],

            // Santiago del Estero
            ['descripcion' => 'Robles', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Banda', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Figueroa', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Choya', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Añatuya', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'General Taboada', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Sarmiento', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'San Martín', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Salavina', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Avellaneda', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Guasayán', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Copo', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Pellegrini', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Jiménez', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Atamisqui', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Aguirre', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Rivadavia', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Mitre', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Quebrachos', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Juan F. Ibarra', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Juan Felipe Ibarra', 'provincia_id' => $provincias['Santiago del Estero']],  // Alias para compatibilidad
            ['descripcion' => 'Loreto', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Ojo de Agua', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'San Martín', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Salavina', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Avellaneda', 'provincia_id' => $provincias['Santiago del Estero']],
            ['descripcion' => 'Santiago del Estero', 'provincia_id' => $provincias['Santiago del Estero']],


            // Tierra del Fuego
            ['descripcion' => 'Río Grande', 'provincia_id' => $provincias['Tierra del Fuego']],
            ['descripcion' => 'Ushuaia', 'provincia_id' => $provincias['Tierra del Fuego']],

            // Tucumán
            ['descripcion' => 'Capital', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Chicligasta', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Monteros', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Tafí Viejo', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Cruz Alta', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Burruyacú', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Trancas', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Yerba Buena', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Leales', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Lules', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Famaillá', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Río Chico', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Simoca', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Tafí del Valle', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Graneros', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'La Cocha', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Juan B. Alberdi', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Cruz Alta', 'provincia_id' => $provincias['Tucumán']],
            ['descripcion' => 'Juan Francisco Borges', 'provincia_id' => $provincias['Tucumán']],
        
    ];

        DB::table('departamentos')->insert($departamentos);
    }
}
