services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000" # Laravel (php artisan serve)
      - "5173:5173" # Vite (npm run dev)
    volumes:
      - ./:/var/www/html
 
    environment:
      # Configuracion que Laravel usa para conectarse al contenedor 'mysql'
      DB_CONNECTION: mysql
      DB_HOST: mysql           # Nombre del servicio MySQL en este docker-compose
      DB_PORT: 3306            # Puerto interno del contenedor MySQL (siempre 3306)
      DB_DATABASE: instituto_db
      DB_USERNAME: root
      DB_PASSWORD: '1234'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: instituto_db
    ports:
      - "3310:3306" 
    volumes:
      - dbdata:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  dbdata:
